const materials = {
    hinncasaverde: require('./Ar3dObjects/hinncasaverde.mtl'),
    casamuseo707: require('./Ar3dObjects/casamuseo707.mtl'),
    hoteldoncarlos: require('./Ar3dObjects/hoteldoncarlos.mtl'),
    familiamadriz: require('./Ar3dObjects/familiamadriz.mtl'),
    hoteldunninn: require('./Ar3dObjects/hoteldunninn.mtl'),
    hotelhemingway: require('./Ar3dObjects/hotelhemingway.mtl'),
    eliaspages: require('./Ar3dObjects/eliaspages.mtl'),
    casa936: require('./Ar3dObjects/casa936.mtl'),
    castillodelmoro: require('./Ar3dObjects/castillodelmoro.mtl'),
    av5ycalles5y7: require('./Ar3dObjects/av5ycalles5y7.mtl'),
    quesadaavendano: require('./Ar3dObjects/quesadaavendano.mtl'),
    familiaolle: require('./Ar3dObjects/familiaolle.mtl'),
    hoteltenerife: require('./Ar3dObjects/hoteltenerife.mtl'),
    serranobonilla: require('./Ar3dObjects/serranobonilla.mtl'),
    calvopena: require('./Ar3dObjects/calvopena.mtl'),
    aguilarbolandi: require('./Ar3dObjects/aguilarbolandi.mtl'),
    obregonloria: require('./Ar3dObjects/obregonloria.mtl'),
    alvarezmelgar: require('./Ar3dObjects/alvarezmelgar.mtl'),
    huetequiroz: require('./Ar3dObjects/huetequiroz.mtl'),
    casaverde: require('./Ar3dObjects/casaverde.mtl'),
    joaquintinoco: require('./Ar3dObjects/joaquintinoco.mtl'),
    alianzaFrancesa: require('./Ar3dObjects/alianzaen000final.mtl'),
    herrerodelpera: require('./Ar3dObjects/herrerodelpera.mtl'),
    ulateblanco: require('./Ar3dObjects/ulateblanco.mtl'),
    avenida7calle3: require('./Ar3dObjects/avenida7calle3.mtl'),
    brenesmendez: require('./Ar3dObjects/brenesmendez.mtl'),
    anticuariosanangel: require('./Ar3dObjects/anticuariosanangel.mtl'),
    calle5haciaav9: require('./Ar3dObjects/calle5haciaav9.mtl'),
    ciprianoherrero: require('./Ar3dObjects/ciprianoherrero.mtl'),
    cotocuberoOBJ: require('./Ar3dObjects/cotocuberoOBJ.obj'),
    peraltazeller: require('./Ar3dObjects/peraltazeller.mtl'),
    escuelatecnicanacional: require('./Ar3dObjects/escuelatecnicanacional.mtl'),
    calle3Ahaciaav11: require('./Ar3dObjects/calle3Ahaciaav11.mtl'),
    antiguafosforera: require('./Ar3dObjects/antiguafosforera.mtl'),
    centrodecine: require('./Ar3dObjects/centrodecine.mtl'),
    hotelreyamon: require('./Ar3dObjects/hotelreyamon.mtl'),
    antiguedadesgobelino: require('./Ar3dObjects/antiguedadesgobelino.mtl'),
    cotocubero: require('./Ar3dObjects/cotocubero.mtl'),
    gonzalesfeo: require('./Ar3dObjects/gonzalesfeo.mtl'),
};


export default materials;