const images = {
  calle3Ahaciaav11: require('./Ar3dObjects/calle3Ahaciaav11OBJ.obj'),
  casa936: require('./Ar3dObjects/casa936OBJ.obj'),
  hoteldoncarlos: require('./Ar3dObjects/hoteldoncarlosOBJ.obj'),
  antiguedadesgobelino: require('./Ar3dObjects/antiguedadesgobelinoOBJ.obj'),
  joaquintinoco: require('./Ar3dObjects/joaquintinocoOBJ.obj'),
  serranobonilla: require('./Ar3dObjects/serranobonillaOBJ.obj'),
  familiaolle: require('./Ar3dObjects/familiaolleOBJ.obj'),
  calle5haciaav9: require('./Ar3dObjects/calle5haciaav9OBJ.obj'),
  hotelreyamon: require('./Ar3dObjects/hotelreyamonOBJ.obj'), 
  alvarezmelgar: require('./Ar3dObjects/alvarezmelgarOBJ.obj'),
  ciprianoherrero: require('./Ar3dObjects/ciprianoherreroOBJ.obj'),
  anticuariosanangel: require('./Ar3dObjects/anticuariosanangelOBJ.obj'),
  quesadaavendano: require('./Ar3dObjects/quesadaavendanoOBJ.obj'),
  ulateblanco: require('./Ar3dObjects/ulateblancoOBJ.obj'),
  hoteltenerife: require('./Ar3dObjects/hoteltenerifeOBJ.obj'),
  centrodecine: require('./Ar3dObjects/centrodecineOBJ.obj'),
  eliaspages: require('./Ar3dObjects/eliaspagesOBJ.obj'),
  calvopena: require('./Ar3dObjects/calvopenaOBJ.obj'),
  brenesmendez: require('./Ar3dObjects/brenesmendezOBJ.obj'),
  huetequiroz: require('./Ar3dObjects/huetequirozOBJ.obj'),
  herrerodelpera: require('./Ar3dObjects/herrerodelperaOBJ.obj'),
  av5ycalles5y7: require('./Ar3dObjects/av5ycalles5y7OBJ.obj'),
  alianzaFrancesa: require('./Ar3dObjects/alianzaen000finalOBJ.obj'),
  gonzalesfeo: require('./Ar3dObjects/gonzalesfeoOBJ.obj'),
  aguilarbolandi: require('./Ar3dObjects/aguilarbolandiOBJ.obj'),
  antiguafosforera: require('./Ar3dObjects/antiguafosforeraOBJ.obj'),
  hotelhemingway: require('./Ar3dObjects/hotelhemingwayOBJ.obj'),
  avenida7calle3: require('./Ar3dObjects/avenida7calle3OBJ.obj'),
  casamuseo707: require('./Ar3dObjects/casamuseo707OBJ.obj'),
  casaverde: require('./Ar3dObjects/casaverdeOBJ.obj'),
  peraltazeller: require('./Ar3dObjects/peraltazellerOBJ.obj'),
  hoteldunninn: require('./Ar3dObjects/hoteldunninnOBJ.obj'),
  hinncasaverde: require('./Ar3dObjects/hinncasaverdeOBJ.obj'),
  obregonloria: require('./Ar3dObjects/obregonloriaOBJ.obj'),
  familiamadriz: require('./Ar3dObjects/familiamadrizOBJ.obj'),
  castillodelmoro: require('./Ar3dObjects/castillodelmoroOBJ.obj'),
  escuelatecnicanacional: require('./Ar3dObjects/escuelatecnicanacionalOBJ.obj'),
  hotelAmstelAmon: require('./Ar3dObjects/HotelamstelamonOBJ.obj'),
};
  
  
  export default images;

